### ISSUE TITLE
Minor bug in error reporting ldap connection on server side

### ISSUE THREAD

**Issue by copumpkin** [AdRoll/hologram#10]
```go
	bindErr := ldapServer.Bind(config.LDAP.Bind.DN, config.LDAP.Bind.Password)
	if bindErr != nil {
		log.Error("Could not bind to LDAP! %s", err.Error())
```

The `Bind` call is saved to `bindErr`, but the error message attempts to print `err`, which at that point will be `nil`. This leads to a nil pointer dereference error instead of the actual desired error message :smile:

**Comment by frangarciam** [comment]
Opened https://github.com/AdRoll/hologram/pull/17

Thanks for all the bug reports!

**Comment by zylad** [comment]
Merged, thanks.
