### ISSUE TITLE
Hardcoded domain name in usercache.go

### ISSUE THREAD

**Issue by copumpkin** [AdRoll/hologram#12]
You have

```go
	searchRequest := ldap.NewSearchRequest(
		"dc=keeponprovoking,dc=com",
```

Which should probably be somewhat configurable :smile:

**Comment by copumpkin** [comment]
There's another one in server.go

**Comment by frangarciam** [comment]
Had an internal ticket for this, good catch :)

Opened https://github.com/AdRoll/hologram/pull/15

**Comment by zylad** [comment]
Merged! Thanks for spotting that.
