### ISSUE TITLE
Configurable username field

### ISSUE THREAD

**Issue by copumpkin** [AdRoll/hologram#18]
I'm using hologram against an active directory server, and in usercache.go:

```go
filter, []string{"sshPublicKey", "cn"},
username := entry.GetAttributeValue("cn")
```

it would be nice if that `cn` field were configurable to be `sAMAccountName`, which is the Microsoft-flavored way to get a username.

**Comment by frangarciam** [comment]
Makes sense, we'll get it added at some point :)
