### ISSUE TITLE
Have intermediate .go files checked in repo

### ISSUE THREAD

**Issue by frangarciam** [AdRoll/hologram#20]
Instead of rebuilding the protobuf definitions or the bindata assets on every build the intermediate .go files they generate should be checked in the repository already, and only regenerated when the source changes (using go generate)

This will simplify our build process and the dependencies needed to build and test hologram (as opposed to actually hacking on its internals) and will potentially get us to the point where hologram is go gettable

**Comment by frangarciam** [comment]
https://github.com/AdRoll/hologram/pull/21

**Comment by zylad** [comment]
This simplifies things a lot. Merged and thanks!
