### ISSUE TITLE
Replace current makefile with something more generic

### ISSUE THREAD

**Issue by frangarciam** [AdRoll/hologram#23]
Our current makefile assumes you're developing on a mac, that all your clients will also be macs and that your server is going to be ubuntu (or at least debian) based.

I propose we simplify it and allow it to be more flexible, by ensuring the following:
- We should be able to build and use hologram just by doing "go get github.com/AdRoll/hologram/..."
- The build process should be as standard as possible (even getting rid of the dependency for gox, if we can just cross-compile by setting GOOS or using a docker container) so all binaries appear in the expected places.
- Use our makefile (or rake or whatever) to build rpm/deb/pkg packages for both client and server on demand (but there's no point on building all packages when doing "make")

**Comment by frangarciam** [comment]
https://github.com/AdRoll/hologram/pull/22 is a first step in that direction

**Comment by zylad** [comment]
I like the overall idea. Also merged https://github.com/AdRoll/hologram/pull/22 thanks!
