### ISSUE TITLE
user.Current issue with new build process

### ISSUE THREAD

**Issue by copumpkin** [AdRoll/hologram#32]
`hologram use` calls `user.Current()` (why? SSH authentication on the server side seems to just iterate over all known SSH keys) which seems to fail on darwin when cross-compiled from linux:

https://github.com/golang/go/issues/6376

**Comment by frangarciam** [comment]
Thanks for catching that, seems like even using the new packages myself for a couple of days was not enough!

Yep, that's a bug alright, we try to avoid things that might depend on cgo on other parts of the code but seems like that one slipped through. I'll fix it on Monday, either removing any reference to the user or relying on a more portable method get the current user.

This gives me another incentive to keep trying to improve our testing framework, which should be easier now that we can automate our builds.

**Comment by copumpkin** [comment]
Still curious what the username is used for there, if you have a chance to explain! I tried tracing it through the code but as far as I could tell, they don't get used on the server. The `AssumeRoleMsg` gets populated with the user but that doesn't seem to ever get read back out?

**Comment by frangarciam** [comment]
From what I can see, the username was used at some point in an older version (before hologram was open sourced). From my testing it seems safe to delete and I'll have a PR doing that shortly, but I want to do some more testing first to ensure compatibility (new client with old server, old server with new client, etc...)

Thanks again for reporting and sorry we let this slip, we're working on tightening our testing process.
