### ISSUE TITLE
Build with travis ci and publish artifacts to the tagged release?

### ISSUE THREAD

**Issue by willejs** [AdRoll/hologram#4]
Can this be done?

**Comment by frangarciam** [comment]
As a first step for this I have added travis ci support for testing. Next step would be to actually generate artifacts (I'm thinking at least rpm and deb) and upload them somewhere. PR is https://github.com/AdRoll/hologram/pull/19

**Comment by zylad** [comment]
https://github.com/AdRoll/hologram/pull/19 has been merged, thanks.
