### ISSUE TITLE
Explain hologram boot?

### ISSUE THREAD

**Issue by copumpkin** [AdRoll/hologram#5]
https://github.com/AdRoll/hologram/blob/master/agent/support/darwin/hologram-boot.sh mentions the AdRoll server specifically. Is the script intended for public consumption?

**Comment by frangarciam** [comment]
It seems like that fell through the cracks when reviewing the code, thanks for catching it!

We've created a pull request for making this script generic: https://github.com/AdRoll/hologram/pull/6

**Comment by miguellara** [comment]
Fixed in eb42ed4e6f5b86a2ef155e9572aa3ba8aa05c101

**Comment by copumpkin** [comment]
Thanks!
