### ISSUE TITLE
Role alias system

### ISSUE THREAD

**Issue by copumpkin** [AdRoll/hologram#52]
Instead of having to remember a bunch of ugly ARNs, it would be nice if the `hologram` CLI tool looked at some sort of config file (could default to `~/.hologram` perhaps) that listed human-readable alias mappings for full ARNs. For example:

```
[Aliases]
prod-zomg = arn:aws:iam::123456789012:role/ZOMG
whoa-wtf = arn:aws:iam::09876543210:role/muahahhaa
```

Then `hologram use prod-zomg` would do the obvious thing.

**Comment by silversupreme** [comment]
A JSON format would probably be better for this, considering that that's the format we use elsewhere. :)

Otherwise, great idea and I'd love to see support for this. :+1:

**Comment by copumpkin** [comment]
Extending this a step further, I'm thinking we could have separate aliases for account numbers and roles: then instead of putting hyphens in my role aliases, I can make an account alias for `prod` and type `hologram use prod rolefoo`. Does that still make sense? It seems like it would allow for more structure across accounts, rather than expecting people to make a cartesian product of role/account pairs (`prod-foo`, `prod-bar`, `dev-foo`, `dev-bar`, etc.)

**Comment by walterking** [comment]
Master now has account aliases.  With `{prod: "arn:aws:iam::123456789012"}`, `hologram use prod/foo` will give you foo role on prod account
