### ISSUE TITLE
No ability to easily open AWS console using hologram credentials

### ISSUE THREAD

**Issue by ryansydnor** [AdRoll/hologram#67]
I'm envisioning a CLI (https://github.com/AdRoll/hologram/issues/37) or a chrome extension that uses hologram provided credentials to open the AWS console. Do you think something like this would be useful?

**Comment by ryansydnor** [comment]
I went ahead and built this. Check out [Holochrome](https://github.com/ryansydnor/holochrome). You can grab it directly from the [Chrome Web Store](https://chrome.google.com/webstore/detail/holochrome/fgnplojdffjfbcmoldcfdoikldnogjpa).

**Comment by walterking** [comment]
thats awesome, we'll put a link to it in our readme

**Comment by ryansydnor** [comment]
Cool! That'd be awesome. I'll close the issue now. Let me know if you have any follow up questions about the extension...

**Comment by walterking** [comment]
https://github.com/Adroll/hologram#related-projects

"Rotate session seamlessly without being logged out" would be amazing, i think my account manager is tired of me asking for more than an hour expiration.  I've tried [this](https://github.com/gitlon/CASTER) but shibboleth didnt work all that well with it.

**Comment by ryansydnor** [comment]
Agree! I *tried* to do that, but basically failed. I grab a new session token every [20 minutes](https://github.com/ryansydnor/holochrome/blob/master/holochrome/script.js#L134-L136). Unfortunately, the AWS console doesn't react well to the "injection" of new credentials. It seems like whenever the session cookie changes at all, it logs you out. I've had inconsistent behavior with this approach - sometimes it logs me out completely and redirects, sometimes it gives me a "you've been logged out" popup, and sometimes it just keeps chugging along happily. Would love any/all help solidifying this!

Would you be up for moving this discussion to the holochrome repo?
