### ISSUE TITLE
Provide better error message when hologram-agent is not running

### ISSUE THREAD

**Issue by aelsabbahy** [AdRoll/hologram#69]
Currently when the hologram-agent is not running a user gets the following cryptic error message:
`dial tcp: missing address`

It would be much more helpful if the user is notified that the hologram-agent isn't running.

**Comment by walterking** [comment]
Latest is:

[ERROR  ] 2017-01-11T21:02:42-08:00 Unable to connect to hologram socket.  Is hologram-agent running? Error: dial unix /tmp/hologram.sock: connect: no such file or directory
