### ISSUE TITLE
Go 1.4 builds as specified in the Dockerfile fail on macOS Sierra

### ISSUE THREAD

**Issue by copumpkin** [AdRoll/hologram#80]
Go reimplements its own syscall interface on OSX instead of using `libSystem` as Apple recommends/requires. Because of that, if Apple changes their syscall ABI, Go programs can break, and that happened with Sierra.

More detail here: https://github.com/golang/go/commit/2da5633eb9091608047881953f75b489a3134cdc

I have it working again by just switching the Hologram Dockerfile to use 1.7 instead of 1.4, but haven't had a chance to put together a proper PR yet. If someone wants to make the one-character change (plus a comment character) before I get to the PR, please be my guest 😄

**Comment by adriandoolittle** [comment]
Thanks!  Yes, I have a PR for this we'll be merging in shortly.  Thanks for reporting.

**Comment by copumpkin** [comment]
Great, thanks for the quick response!

**Comment by adriandoolittle** [comment]
Had to make a couple other changes to the Dockerfile, but looks good now.
