### ISSUE TITLE
Metadata available on network

### ISSUE THREAD

**Issue by walterking** [AdRoll/hologram#95]
I came across https://github.com/99designs/aws-vault/issues/198, not sure if it applies and have nothing to test with, but someone should probably check if this issue applies to hologram or not as it could mean leaking credentials to anyone on the network

**Comment by walterking** [comment]
I verified this, if you do `arp -s 169.254.169.254 <victim mac address>` then you can just curl the metadata address and steal credentials as long as you are on the same network(ie, coffee shop).

**Comment by dialtone** [comment]
https://github.com/99designs/aws-vault/commit/9053ba8138ea948c75d2a0cc4ad88636ac0a9fd6

this is how they fixed it.

**Comment by copumpkin** [comment]
Ouch, this seems pretty bad. Can we steal that remote address check for hologram?

**Comment by dialtone** [comment]
Yeah, should be pretty easy to do

**Comment by dialtone** [comment]
https://github.com/AdRoll/hologram/pull/97 This should do it.

**Comment by BillMedernach** [comment]
Tested this with the latest version of Hologram and this vulnerability is fixed.
